export interface TagLinkI {
    name: string
    target: string
    url: string
}

export const tagDataMap: Map<string, TagLinkI> = new Map([
    // languages / libs / frameworks
    ["aem", { name: "Adobe Experience Manager", target: "_blank", url: "https://business.adobe.com/products/experience-manager/adobe-experience-manager.html" }],
    ["agile", { name: "Agile", target: "_blank", url: "https://www.atlassian.com/agile" }],
    ["appium", { name: "Appium", target: "_blank", url: "https://appium.io/docs/en/latest/" }],
    ["anime", { name: "Anime JS", target: "_blank", url: "https://animejs.com/" }],
    ["aws", { name: "AWS", target: "_blank", url: "https://aws.amazon.com/" }],
    ["aws:apiGateway", { name: "AWS: API Gateway", target: "_blank", url: "https://aws.amazon.com/api-gateway/" }],
    ["aws:cloudfront", { name: "AWS: CloudFront", target: "_blank", url: "https://aws.amazon.com/cloudfront/" }],
    ["aws:lambda", { name: "AWS: Lambda", target: "_blank", url: "https://aws.amazon.com/lambda/" }],
    ["aws:rds", { name: "AWS: RDS", target: "_blank", url: "https://aws.amazon.com/rds/" }],
    ["aws:route53", { name: "AWS: Route53", target: "_blank", url: "https://aws.amazon.com/route53/" }],
    ["aws:s3", { name: "AWS: S3", target: "_blank", url: "https://aws.amazon.com/s3/" }],
    ["azure", { name: "Azure", target: "_blank", url: "https://azure.microsoft.com/en-us/" }],
    ["babel", { name: "Babel", target: "_blank", url: "https://babeljs.io/" }],
    ["bootstrap", { name: "Bootstrap", target: "_blank", url: "https://getbootstrap.com/" }],
    ["c++", { name: "C++", target: "_blank", url: "https://cplusplus.com/" }],
    ["css", { name: "CSS", target: "_blank", url: "https://developer.mozilla.org/en-US/docs/Web/CSS" }],
    ["django", { name: "DJango", target: "_blank", url: "https://www.djangoproject.com/" }],
    ["djangoCrispyForms", { name: "DJango Crispy Forms", target: "_blank", url: "https://django-crispy-forms.readthedocs.io/en/latest/" }],
    ["docker", { name: "Docker", target: "_blank", url: "https://www.docker.com/" }],
    ["express", { name: "Express JS", target: "_blank", url: "https://expressjs.com/" }],
    ["figma", { name: "Figma", target: "_blank", url: "https://www.figma.com/" }],
    ["flask", { name: "Flask", target: "_blank", url: "https://flask.palletsprojects.com/en/latest/#" }],
    ["git", { name: "Git", target: "_blank", url: "https://git-scm.com/" }],
    ["golang", { name: "Go", target: "_blank", url: "https://go.dev/" }],
    ["googlemaps", { name: "GoogleMaps", target: "_blank", url: "https://developers.google.com/maps" }],
    ["graphql", { name: "GraphQL", target: "_blank", url: "https://graphql.org/" }],
    ["groovy", { name: "Groovy", target: "_blank", url: "https://groovy-lang.org/" }],
    ["heroku", { name: "Heroku", target: "_blank", url: "https://www.heroku.com/" }],
    ["html", { name: "HTML", target: "_blank", url: "https://html.spec.whatwg.org/multipage/" }],
    ["java", { name: "Java", target: "_blank", url: "https://www.java.com/en/" }],
    ["javaFX", { name: "JavaFX", target: "_blank", url: "https://openjfx.io/" }],
    ["javascript", { name: "JavaScript", target: "_blank", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript" }],
    ["jenkins", { name: "Jenkins", target: "_blank", url: "hhttps://www.jenkins.io" }],
    ["jest", { name: "Jest", target: "_blank", url: "https://jestjs.io/" }],
    ["jira", { name: "Jira", target: "_blank", url: "https://www.atlassian.com/software/jira" }],
    ["jquery", { name: "JQuery", target: "_blank", url: "https://jquery.com/" }],
    ["jwt", { name: "JWT", target: "_blank", url: "https://jwt.io/" }],
    ["linux", { name: "Linux", target: "_blank", url: "https://www.linux.org/" }],
    ["magnolia", { name: "Magnolia CMS", target: "_blank", url: "https://www.magnolia-cms.com/" }],
    ["maven", { name: "Maven", target: "_blank", url: "https://maven.apache.org/" }],
    ["microsoftServer", { name: "Microsoft SQL Server", target: "_blank", url: "https://www.microsoft.com/en-us/sql-server/" }],
    ["mysql", { name: "MySQL", target: "_blank", url: "https://www.mysql.com/" }],
    ["node", { name: "Node JS", target: "_blank", url: "https://nodejs.org/en" }],
    ["nodemailer", { name: "Nodemailer", target: "_blank", url: "https://nodemailer.com/" }],
    ["nose", { name: "nose", target: "_blank", url: "https://nose.readthedocs.io/en/latest/" }],
    ["npm", { name: "npm", target: "_blank", url: "https://www.npmjs.com/" }],
    ["numpy", { name: "NumPy", target: "_blank", url: "https://numpy.org/" }],
    ["oauth", { name: "OAuth", target: "_blank", url: "https://oauth.net/" }],
    ["okta", { name: "Okta", target: "_blank", url: "https://www.okta.com/" }],
    ["pandas", { name: "Pandas", target: "_blank", url: "https://pandas.pydata.org/" }],
    ["pip", { name: "pip", target: "_blank", url: "https://pypi.org/" }],
    ["postgres", { name: "PostgreSQL", target: "_blank", url: "https://www.postgresql.org/" }],
    ["postman", { name: "Postman", target: "_blank", url: "https://www.postman.com/" }],
    ["pytest", { name: "pytest", target: "_blank", url: "https://docs.pytest.org/en/" }],
    ["python", { name: "Python", target: "_blank", url: "https://www.python.org/" }],
    ["react", { name: "React JS", target: "_blank", url: "https://react.dev/" }],
    ["reactBootstrap", { name: "React Bootstrap", target: "_blank", url: "https://react-bootstrap.netlify.app/" }],
    ["redux", { name: "Redux JS", target: "_blank", url: "https://redux.js.org/" }],
    ["sass", { name: "SASS", target: "_blank", url: "https://sass-lang.com/" }],
    ["sauceLabs", { name: "Sauce Labs", target: "_blank", url: "https://saucelabs.com/" }],
    ["selenium", { name: "Selenium", target: "_blank", url: "https://www.selenium.dev/" }],
    ["sqlite", { name: "SQLite", target: "_blank", url: "https://www.sqlite.org/index.html" }],
    ["testRail", { name: "TestRail", target: "_blank", url: "https://www.testrail.com/" }],
    ["theTradeDesk", { name: "The Trade Desk", target: "_blank", url: "https://www.thetradedesk.com/us" }],
    ["typescript", { name: "TypeScript", target: "_blank", url: "https://www.typescriptlang.org/" }],
    ["vite", { name: "Vite", target: "_blank", url: "https://vitejs.dev/" }],
    ["webpack", { name: "webpack", target: "_blank", url: "https://webpack.js.org" }],
])
